# tmux config (see scripts folder for logic)
set -g prefix C-a
unbind C-b
bind C-a send-prefix
set -g mouse on
set -g status-interval 1

set -g status-right "#(~/ .tmux/scripts/cpu.sh) #(~/ .tmux/scripts/mem.sh) #(~/ .tmux/scripts/net.sh) %Y-%m-%d %H:%M:%S"
